apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zhpa-springboot-app
  namespace: argocd
spec:
  project: default #every application belongs to a single project

  source:
    repoURL: https://github.com/zsmn/k8scd
    targetRevision: HEAD
    path: k8s/config/springboot-app
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: zhpa-springboot-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
